// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPFMxGV5PttAaY1CDb1upoRsqNCZnp5ms',
    appId: '1:992956421983:web:b5da42784edcd3840648ea',
    messagingSenderId: '992956421983',
    projectId: 'intellinest-32cd1',
    authDomain: 'intellinest-32cd1.firebaseapp.com',
    storageBucket: 'intellinest-32cd1.appspot.com',
    measurementId: 'G-30RN85VHTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPm9n_eYuDN3JLUJd0ETMzaXg7pAm7w_k',
    appId: '1:992956421983:android:60d56d81de4711ba0648ea',
    messagingSenderId: '992956421983',
    projectId: 'intellinest-32cd1',
    storageBucket: 'intellinest-32cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7e1JGy6zOLy42_6YPHWICL7lfjuWJxhI',
    appId: '1:992956421983:ios:658bd40c7fc986b80648ea',
    messagingSenderId: '992956421983',
    projectId: 'intellinest-32cd1',
    storageBucket: 'intellinest-32cd1.appspot.com',
    iosBundleId: 'com.example.intellinest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7e1JGy6zOLy42_6YPHWICL7lfjuWJxhI',
    appId: '1:992956421983:ios:b1bcb97fa806602e0648ea',
    messagingSenderId: '992956421983',
    projectId: 'intellinest-32cd1',
    storageBucket: 'intellinest-32cd1.appspot.com',
    iosBundleId: 'com.example.intellinest.RunnerTests',
  );
}
